### ISSUE TITLE
Could not connect to sci-hub

### ISSUE THREAD

**Issue by MrUnknown789556** [benmuth/papers-dl#2]
Downloading papers_dl-0.0.20-py3-none-any.whl (11 kB)
Installing collected packages: papers-dl
  Attempting uninstall: papers-dl
    Found existing installation: papers-dl 0.0.19
    Uninstalling papers-dl-0.0.19:
      Successfully uninstalled papers-dl-0.0.19
Successfully installed papers-dl-0.0.20

C:\Users\fn31>papers-dl fetch "10.1016/j.cub.2019.11.030"
ERROR:root:Couldn't connect to http://sci-hub.vk/10.1016/j.cub.2019.11.030: Cannot connect to host sci-hub.vk:80 ssl:default [getaddrinfo failed]
ERROR:root:Couldn't connect to https://sci-hub.do/10.1016/j.cub.2019.11.030: Cannot connect to host sci-hub.do:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]
ERROR:root:Couldn't connect to https://sci-hub.se/10.1016/j.cub.2019.11.030: Cannot connect to host sci-hub.se:443 ssl:default [Semaforens timeout-periode er udløbet]
ERROR:root:Couldn't connect to http://sci-hub.is/10.1016/j.cub.2019.11.030: Cannot connect to host sci-hub.se:443 ssl:default [Semaforens timeout-periode er udløbet]
ERROR:root:Couldn't connect to https://sci.hubg.org/10.1016/j.cub.2019.11.030: Server disconnected
.\Parrots Voluntarily Help Each Other to Obtain Food Rewards.pdf

/Frank

**Comment by benmuth** [comment]
This is just misleading logging statements. The last line shows the path of the document that was downloaded, so this was actually a successful fetch job.

Some Sci-Hub hosts won't be able to be used, but that's expected. I'll change these logging statements to be more clear.

**Comment by MrUnknown789556** [comment]
Dear Ben.
Most people don't want or need some logging information, if everything goes ok.
If something goes wrong, then it is nice to have some info, to give to you for information for further improvement of your excellent program
People not familiar with Python (like me), get a litte bit freightened with this many lines of error information.
You are certainly a speialist into Python. Us "normal" people just want a yes or no, if the program succeded getting the PDF or not.
Maybe all the logging should instead be written into an error log file.
By the way, I just tried the program again with another DOI.
Here is what is logged on screen.
#####################################################################
C:\Users\fn31>papers-dl fetch 10.1016/j.compstruct.2024.118392ERROR:root:Couldn't connect to http://sci-hub.vk/10.1016/j.compstruct.2024.118392: Cannot connect to host sci-hub.vk:80 ssl:default [getaddrinfo failed]ERROR:root:Couldn't connect to https://sci-hub.do/10.1016/j.compstruct.2024.118392: Cannot connect to host sci-hub.do:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]ERROR:root:Couldn't connect to https://sci-hub.se/10.1016/j.compstruct.2024.118392: Cannot connect to host sci-hub.se:443 ssl:default [Semaforens timeout-periode er udløbet]ERROR:root:Couldn't connect to http://sci-hub.is/10.1016/j.compstruct.2024.118392: Cannot connect to host sci-hub.se:443 ssl:default [Semaforens timeout-periode er udløbet]ERROR:root:Couldn't connect to https://sci.hubg.org/10.1016/j.compstruct.2024.118392: Cannot connect to host sci.hubg.org:443 ssl:default [Semaforens timeout-periode er udløbet]Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main  File "<frozen runpy>", line 88, in _run_code  File "C:\Users\fn31\AppData\Local\Programs\Python\Python312\Scripts\papers-dl.exe\__main__.py", line 7, in <module>  File "C:\Users\fn31\AppData\Local\Programs\Python\Python312\Lib\site-packages\papers_dl.py", line 160, in main    asyncio.run(run())  File "C:\Users\fn31\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run    return runner.run(main)           ^^^^^^^^^^^^^^^^  File "C:\Users\fn31\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run    return self._loop.run_until_complete(task)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\fn31\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete    return future.result()           ^^^^^^^^^^^^^^^  File "C:\Users\fn31\AppData\Local\Programs\Python\Python312\Lib\site-packages\papers_dl.py", line 147, in run    result = await args.func(args)             ^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\fn31\AppData\Local\Programs\Python\Python312\Lib\site-packages\papers_dl.py", line 36, in fetch    pdf_content = await fetch_utils.fetch(                  ^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\fn31\AppData\Local\Programs\Python\Python312\Lib\site-packages\fetch\fetch_utils.py", line 81, in fetch    logging.info("PDF urls: %s" % "\n".join(urls))                                  ^^^^^^^^^^^^^^^TypeError: sequence item 0: expected str instance, NoneType found
C:\Users\fn31>
#####################################################################


/Frank



    Den torsdag den 18. juli 2024 kl. 21.02.14 CEST skrev Ben Muthalaly ***@***.***>:  
 
 


This is just misleading logging statements. The last line shows the path of the document that was downloaded, so this was actually a successful fetch job.

Some Sci-Hub hosts won't be able to be used, but that's expected. I'll change these logging statements to be more clear.

**Comment by benmuth** [comment]
@MrUnknown789556 I can definitely understand how it's overwhelming to get a bunch of noisy information on the screen at once. Thanks for reporting this. This should be better now.
